[default]
extend-ignore-re = [
  "\\b[0-9A-Za-z+/]{91}(=|==)?\\b",  # base64 strings
  "[0-9a-fA-F]{7,}",                 # git commit hashes
  "\\b[0-9A-Za-z+/]{33,}(=|==)?\\b", # SHA/tpub/adresses etc strings
]

[default.extend-words]
# code stuff
Tesselation = "Tesselation"
tesselation = "tesselation"
Missings = "Missings"

[type.gitignore]
extend-glob = [".gitignore"]
check-file = false

[type.bib]
extend-glob = ["*.bib"]
check-file = false
