[projects]

  [projects.default]
  contents = [
    "preface",
    "why_julia",
    "julia_basics",
    "dataframes",
    "dataframes_load_save",
    "dataframes_indexing",
    "dataframes_select",
    "dataframes_join",
    "dataframes_transform",
    "dataframes_groupby_combine",
    "dataframes_missing",
    "dataframes_performance",
    "dataframesmeta",
    "dataframesmeta_macros",
    "dataframesmeta_select",
    "dataframesmeta_transform",
    "dataframesmeta_subset",
    "dataframesmeta_orderby",
    "dataframesmeta_combine",
    "dataframesmeta_chain",
    "data_vis_makie",
    "data_vis_makie_cairo",
    "data_vis_makie_attributes",
    "data_vis_makie_themes",
    "data_vis_makie_latex",
    "data_vis_makie_colors",
    "data_vis_makie_layouts",
    "data_vis_makie_glmakie",
    "data_vis_makie_recipe",
    "data_vis_aog",
    "data_vis_aog_plots",
    "data_vis_aog_stats",
    "data_vis_aog_custom",
    "data_vis_aog_layouts",
    #"stats",
    #"stats_distributions",
    #"stats_vis",
    "appendix",
    "notation",
    "references"
  ]
  port = 8006

  # Extra directories to be copied.
  extra_directories = [
    "images"
  ]

  online_url = "https://juliadatascience.io"

  output_filename = "juliadatascience"
