[projects]

  [projects.default]
  contents = [
    "preface",
    "why_julia",
    "julia_101",
    "dataframes",
    "load_save",
    "indexing",
    "select",
    "join",
    "plots",
    "makie",
    "appendix",
    "references"
  ]
  port = 8006

  # Extra directories to be copied.
  extra_directories = [
    "images",
    "files"
  ]

  output_filename = "juliadatascience"
