name = "JDS"
uuid = "6c596d62-2771-44f8-8373-3ec4b616ee9d"
authors = ["Jose Storopoli", "Rik Huijzer", "Lazaro Alonso"]
version = "0.1.0"

[deps]
AlgebraOfGraphics = "cbdf2221-f076-402e-a563-3d30da359d67"
Books = "939d5c6b-51ae-42e7-97ca-7564d0d4ad91"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
XLSX = "fdbf4ff8-1666-58a4-91e7-1b58723a45e0"

[compat]
AlgebraOfGraphics = "0.4"
Books = "0.7"
CSV = "0.8"
CairoMakie = "0.6"
CategoricalArrays = "0.10"
DataFrames = "1.1"
Makie = "0.15"
Plots = "1.19"
Reexport = "1.1"
StatsPlots = "0.14"
XLSX = "0.7"
