name: CompatHelper

on:
  schedule:
    - cron: '00 04 * * 6'
  workflow_dispatch:

jobs:
  CompatHelper:
    runs-on: ubuntu-latest
    steps:
      - name: "Install CompatHelper"
        shell: julia --color=yes {0}
        run: |
          import Pkg
          name = "CompatHelper"
          uuid = "aa819f21-2bde-4658-8897-bab36330d9b7"
          version = "2"
          Pkg.add(; name, uuid, version)

      - name: "Run CompatHelper"
        shell: julia --color=yes {0}
        run: |
          import CompatHelper
          CompatHelper.main()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMPATHELPER_PRIV: ${{ secrets.COMPATHELPER_PRIV }}
